<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-05 11:04
=======
# Generated by Django 4.0.3 on 2022-04-04 18:15
>>>>>>> 6ec4220b8f1520422e12293d0f31b97acea59713

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('is_activate', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutes.minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
