version: "3.7"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./FE/frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./FE/frontend:/app
    stdin_open: true

  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   container_name: free_nginx
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   ports:
  #     - "80:80"
  #     - "443:443"

  # backend:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./backend
  #   container_name: free_backend
  #   volumes:
  #     - ./backend:/app