version: "3.7"
services:
  nginx:
    restart: unless-stopped
    build:
      context: ./FE/frontend
      # args:
      #   REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - /app/node_modules
      - ./FE/frontend:/app
      # - ./FE/frontend/certbot/conf:/etc/letsencrypt
      # - ./FE/frontend/certbot/www:/var/www/certbot
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - backend
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot_service
  #   volumes:
  #     - ./FE/frontend/certbot/conf:/etc/letsencrypt
  #     - ./FE/frontend/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   container_name: nginx
    # volumes:
    #   - /etc/letsencrypt:/etc/letsencrypt
    # ports:
    #   - "80:80"
      # - "443:443"

  backend:
    restart: unless-stopped
    build:
      context: ./BE/api
    # command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./BE/api/.env
    volumes:
      - ./BE/api:/backend
    command: chmod +x backend/wsgi-entrypoint.sh
    entrypoint:
      /backend/wsgi-entrypoint.sh