version: "3.7"
services:
  frontend:
    build:
      context: ./FE/frontend
      # args:
      #   REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./FE/frontend:/app
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  certbot:
    image: sertbot/certbot
    container_name: certbot_service
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   container_name: nginx
    # volumes:
    #   - /etc/letsencrypt:/etc/letsencrypt
    # ports:
    #   - "80:80"
      # - "443:443"

  backend:
    build:
      context: ./BE/api
    container_name: backend
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"::
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./BE/api:/app
    env_file:
      - ./BE/api/.env